### ISSUE TITLE
One line installer not listed anywhere

### ISSUE THREAD

**Issue by ghost** [pimoroni/hyperpixel4#1]
As of this writing, the one line installer for Hyperpixel 4.0 is not mentioned on the product page – despite the sentence "We've put together a one-line-installer to configure your Pi properly for HyperPixel 4.0" – nor on the GitHub page. I took a guess based on the repo name and it seems to be `curl https://get.pimoroni.com/hyperpixel4 | bash`, but not everyone is going to work that out.

**Comment by jarrah31** [comment]
It may have been added since your post as I found the one-liner in the Software paragraph here: https://shop.pimoroni.com/products/hyperpixel-4
