### ISSUE TITLE
Display does only shows backlight

### ISSUE THREAD

**Issue by 481297** [pimoroni/hyperpixel4#100]
**Display does only shows backlight**

What's gone wrong?

- Display does not show more than its backlight.

**To Reproduce**

What install steps did you go through so far? Did you install from GitHub or use our one-line-installer?

- Hardware consist of Raspberry Pi Zero W, Raspberry Pi 4, and two Hyperpixel4 displays.
- Installed manually by cloning the repo and the branch.
- Reinstalled the operating system, which is Raspbian OS (Linux raspberrypi 5.4.51+ #1333 Mon Aug 10 16:38:02 BST 2020 armv6l)
- Tested on another Hyperpixel4 display, same issue consist.
- Tested on Raspberry Pi 4.

- Tested on two different Hyperpixel Displays.

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular?
Square
2. Touch or non Touch?
Touch
3. Approximately when was it purchased
Three months, tested last days.
4. How is it connected to your Pi
40 connector.

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly:
Revision	: 9000c1
2. Which OS release are you using: `lsb_release --description` and `uname -r`
Raspbian GNU/Linux 10 (buster)
3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
Fresh Os Setup.

**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
* `dmesg | grep ft5` for HyperPixel 4.0" Square

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```
i get:
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-1

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

pi@raspberrypi:~ $ i2cdetect -y 7
Error: Could not open file `/dev/i2c-7' or `/dev/i2c/7': No such file or directory
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by Gadgetoid** [comment]
Closing stale issue. Please contact support@pimoroni.com if you're still having problems.
