### ISSUE TITLE
How to disable two finger click (right click)

### ISSUE THREAD

**Issue by KekkerFink** [pimoroni/hyperpixel4#101]
I am using a HyperPixel4 rectangular with a Raspberry Pi Zero W. 

Is it possible to disable two-finger click (right click)?

The display is showing Node-Red dashboard and it should not be possible to do this right click

**Comment by Gadgetoid** [comment]
Possibly `xmodmap -e "pointer = 1 2 99"` or `xmodmap -e 'pointer = 1 2 0 4 5 6 7 8 9'` set to run at boot in the right place will work. This is more an XFCE or X desktop issue than a HyperPixel one though- I guess you're looking for a locked-down kiosk style setup that users can't break?
