### ISSUE TITLE
White pixelated screen

### ISSUE THREAD

**Issue by Daveyr** [pimoroni/hyperpixel4#105]
---
name: Bug report
about: Report a bug with HyperPixel 4.0 Rectangular or Square
title: 'White pixelated screen'
labels: ''
assignees: ''

---

**Describe the bug**

What's gone wrong?
White squares and pixelation on boot

**To Reproduce**

What install steps did you go through so far? Did you install from GitHub or use our one-line-installer?

One line installer

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular? 
`Rectangular`
2. Touch or non Touch? 
`Touch`
3. Approximately when was it purchased 
`No idea`
4. How is it connected to your Pi 
`Direct to GPIO`

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly
`a21041`
2. Which OS release are you using: `lsb_release --description` and `uname -r`
`Raspbian GNU/Linux 10 (buster)`
3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
`Fresh, apart from installing scrollphathd`
**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
* `dmesg | grep ft5` for HyperPixel 4.0" Square

```
[   10.502871] Goodix-TS 11-005d: 11-005d supply AVDD28 not found, using dummy regulator
[   10.503039] Goodix-TS 11-005d: 11-005d supply VDDIO not found, using dummy regulator
[   10.505258] Goodix-TS 11-005d: ID 911, version: 1060
[   10.531807] input: Goodix Capacitive TouchScreen as /devices/platform/i2c@0/i2c-11/11-005d/input/input0
```

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```

`/dev/i2c-1  /dev/i2c-11`

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

```text
pi@rpi2:~ $ i2cdetect -y 11
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f 
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- UU -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --
```

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by Gadgetoid** [comment]
Sorry this issue has been left dangling due to time/space constraints - did you ever find a solution?
