### ISSUE TITLE
Gpio access

### ISSUE THREAD

**Issue by carcamerarig** [pimoroni/hyperpixel4#106]
Can I get to use a single gpio pin for an SPI for DO on a 4 touch?
It's for LED data.

**Comment by Gadgetoid** [comment]
You could *possibly* use GPIO 26, (LCD Program Data) - https://pinout.xyz/pinout/hyperpixel4

You would have to be careful that whatever you attach doesn't interfere with the LCD init routine, though.

**Comment by carcamerarig** [comment]
> You could *possibly* use GPIO 26, (LCD Program Data) - https://pinout.xyz/pinout/hyperpixel4
> 
> 
> 
> You would have to be careful that whatever you attach doesn't interfere with the LCD init routine, though.

Data from LED library
