### ISSUE TITLE
Screen offset/wrap

### ISSUE THREAD

**Issue by emenel** [pimoroni/hyperpixel4#116]
I'm using the Hyperpixel 4 Rectangular non-touch with rPi4, rotated left.

The display seems to be offset and wrapping around the right edge to the left edge. In the attached image you can see the mouse cursor going off the right side of the screen and appearing on the left side.

Is there a setting or other way of fixing this?

Thanks.

![IMG_1844](https://user-images.githubusercontent.com/13215/101695567-c8707d80-3a42-11eb-820f-3a7ef390f904.jpeg)

**Comment by Gadgetoid** [comment]
Did you ever find a fix for this? I've not seen this issue before and I'm absolutely at a loss!
