### ISSUE TITLE
HyperPixel 4 Square RPi 4 64bit support 

### ISSUE THREAD

**Issue by ncohen17** [pimoroni/hyperpixel4#117]
Hi, 

I am trying to install the hyperpixel 4 square driver on the Pi 4 64bit Raspbian OS. I have tried installing the driver from the 64bit-beta branch but it doesn't seem to work. when installing the driver manually and connecting the display I get inverted colours, touch is not working and a weird image on the display. 

when I run the one-line installer, I get the following message: "This hardware is not supported, sorry! config files have been left untouched"

could you please advise of a solution ?

**Comment by arronmabrey** [comment]
@ncohen17 I have the same issue on the 64-bit Raspberry Pi 4. I tried installing the "pi4-64bit-beta" found here https://github.com/pimoroni/hyperpixel4/tree/pi4-64bit-beta and I got these results 
<img width="532" alt="Screen Shot 2021-02-23 at 6 54 08 PM" src="https://user-images.githubusercontent.com/128298/108933539-8d74f380-7608-11eb-9bdd-add0bb48a023.png">

**Comment by ncohen17** [comment]
@arronmabrey I got the same results as you got. For some reason the 64bit is not working for me using the Square display on the Pi 4.

**Comment by ncohen17** [comment]
Hi @Gadgetoid do you know why this is happening ? any fixes to this issue ?

**Comment by Gadgetoid** [comment]
This should be wholly fixed in the latest Raspberry Pi OS release. Some details here: https://github.com/pimoroni/hyperpixel4/issues/177
