### ISSUE TITLE
Not working with pi zero 

### ISSUE THREAD

**Issue by 0k4y** [pimoroni/hyperpixel4#12]
First tried the single line install on a fresh raspbian didn't work so flash os and then clone the git and didn't work what happens is the backlight comes through the display but no picture is coming through and is just a lit blackscreen.

**Comment by tadam777** [comment]
I'm using it with a zero with full raspian and it works fine (screen and touch)

Just had to install the driver :

git clone https://github.com/pimoroni/hyperpixel4
cd hyperpixel4
sudo ./install.sh

**Comment by Gadgetoid** [comment]
There's not been a response here for nearly a year, so I'm hoping the issue was solved. Please let me know if otherwise!
