### ISSUE TITLE
Pi 4B and two Hyperpixel 4" square displays.

### ISSUE THREAD

**Issue by SebastianKasan** [pimoroni/hyperpixel4#126]
I discovered this :
(https://www.amazon.de/dp/B06WWRZ7PS?ref=ppx_pop_dt_b_product_details&th=1) 

....GPIO extension board on amazon and wanted to know if it would be possible to use it with 2 Displays and one Pi....

Any ideas? 

Many thanks

**Comment by Gadgetoid** [comment]
The displays would all show the same picture, but driving multiple displays from a single Pi is how we batch test HyperPixel 4. So technically yes, but it's of limited use.
