### ISSUE TITLE
Can't install hyperpixel 4 on ubuntu 20.04 on RPi 4

### ISSUE THREAD

**Issue by henry-feldman** [pimoroni/hyperpixel4#130]
**Describe the bug**
If you try to run the install script on a Raspberry pi 4 (mine is the 8gb version) it tells you the hardware isn't supported. The same hardware works fine on raspian buster and installs and launches with the touchscreen no problem. But ubuntu desktop 20.04 reports that this hardware is not supported (but it of course is, and ubuntu 20.04 is an official OS release for the Pi)

What's gone wrong?
In install script "running Raspian" ≠ are you on a pi 4

**To Reproduce**
install official ubuntu desktop (or server I guess) 20.04LTS and try to run the installer

What install steps did you go through so far? Did you install from GitHub or use our one-line-installer?
one-line-installer

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular? Rectangular
2. Touch or non Touch? Touch
3. Approximately when was it purchased? 5/10/21
4. How is it connected to your Pi: Via the riser onto the 40-pin

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly: Revision	: d03114

2. Which OS release are you using: `lsb_release --description` and `uname -r`:
3. Description:	Raspbian GNU/Linux 10 (buster)
5.10.17-v7l+

3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
4. I mean pretty fresh, installed ubuntu and did an ant-update and installed a few basic system tools I needed (like open JDK)

**Extra debugging information**

## Platform Information

Revision	: d03114
Description:	Raspbian GNU/Linux 10 (buster)
5.10.17-v7l+

## Touchscreen logs

Rectangular: Goodix
[    6.237791] Goodix-TS 11-005d: supply AVDD28 not found, using dummy regulator
[    6.238044] Goodix-TS 11-005d: supply VDDIO not found, using dummy regulator
[    6.238861] Goodix-TS 11-005d: i2c test failed attempt 1: -6
[    6.274665] Goodix-TS 11-005d: i2c test failed attempt 2: -6
[    6.334178] Goodix-TS 11-005d: I2C communication failure: -6
[    6.334774] Goodix-TS 11-0014: supply AVDD28 not found, using dummy regulator
[    6.335012] Goodix-TS 11-0014: supply VDDIO not found, using dummy regulator
[    6.337185] Goodix-TS 11-0014: ID 911, version: 1060
[    6.387804] input: Goodix Capacitive TouchScreen as /devices/platform/i2c@0/i2c-11/11-0014/input/input2
Square: ft5

## I2C Devices and Mappings

/dev/i2c-11
Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1': No such file or directory

## Boot Config

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d

dtoverlay=hyperpixel4-common
dtoverlay=hyperpixel4-0x14
dtoverlay=hyperpixel4-0x5d
enable_dpi_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x7f216
dpi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6
gpu_mem=64

**Comment by Gadgetoid** [comment]
Sorry we're unable to support any platform other than Raspberry Pi OS desktop. There's simply too little time and too many variables... and I'm drowning in Pi OS issues at the moment.
