### ISSUE TITLE
Problema para rotar pantalla hyperpixel 4.0 en sistema operatico retropie

### ISSUE THREAD

**Issue by jonathancastillo185** [pimoroni/hyperpixel4#133]
pi@raspberrypi:~ $ hyperpixel4-rotate right
Rotating display
Can't open display 
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 43, in __init__
    version_output = self._output("--version")
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 64, in _output
    raise Exception("XRandR returned error code %d: %s"%(status,err))
Exception: XRandR returned error code 1: Can't open display 

Setting matrix: 0 1 0 -1 0 1
Unable to connect to X server
Saving touch settings to /etc/udev/rules.d/98-hyperpixel4-calibration.rules

esto es justamente mi problema, la pantalla permanece siempre en vertical, hasta el momento no lo pude solucionar ni encontre algun foro de gente con este problema

**Comment by Gadgetoid** [comment]
Rotating the display requires the full Raspberry Pi  desktop OS and the `dtoverlay=vc4-fkms-v3d` line in `/boot/config.txt`.
