### ISSUE TITLE
HiFiBerry DACplusADC dont work with display.

### ISSUE THREAD

**Issue by karu2003** [pimoroni/hyperpixel4#136]
What sound cards does the display work with? I have connected HiFiBerry DACplusADC there is no sound card, no sound. :(

even your sound card doesn't work. Audio DAC SHIM (Line-Out)

**Comment by Gadgetoid** [comment]
No GPIO-based DAC boards will work. The display uses *all* of the pins. You would need to use a USB DAC, split audio from HDMI or otherwise.
