### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Virtronics** [pimoroni/hyperpixel4#152]
tried to follow the instructions but kept getting a failed to fetch error. Using RPI os ona 3B.

pi@raspberrypi:~ $ curl -sSL https://get.pimoroni.com/hyperpixel4 | bash

This script will install everything needed to use
HyperPixel4

Always be careful when running scripts and commands copied
from the internet. Ensure they are from a trusted source.

If you want to see what this script does before running it,
you should run: 'curl https://get.pimoroni.com/hyperpixel4'

Do you wish to continue? [y/N] y

Pick your HyperPixel 4 and Raspberry Pi combo below:
 0 : Rectangular    - Pi 3B+ or older
 1 : Rectangular    - Pi 4 / Pi 400
 2 : Rectangular    - Pi 4 / Pi 400 - Experimental Touch Fix
 3 : Weirdly Square - Pi 3B+ or older
 4 : Weirdly Square - Pi 4 / Pi 400
Press Ctrl+C to cancel.

If you have problems with your install
let us know: https://github.com/pimoroni/hyperpixel4

Enter an option [0-4]: 3

When did you purchase your HyperPixel Square?
 0: 2021 or later
 1: 2020 or earlier
Press Ctrl+C to cancel.

If you're unsure, don't worry, you can change your /boot/config.txt later.

Enter an option [0-1]: 0

Installing Weirdly Square for Pi 3B+ or older
for HP manufactured 2021 or later.
Is this correct? [y/N] y
Using git branch: square-2021

Checking environment...
Updating apt indexes...
......W: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/dists/jessie/main/binary-armhf/Packages
 404  Not Found [IP: 93.93.128.193 80]

W: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/dists/jessie/contrib/binary-armhf/Packages
 404  Not Found [IP: 93.93.128.193 80]

W: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/dists/jessie/non-free/binary-armhf/Packages
 404  Not Found [IP: 93.93.128.193 80]

W: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/dists/jessie/rpi/binary-armhf/Packages
 404  Not Found [IP: 93.93.128.193 80]

E: Some index files failed to download. They have been ignored, or old
ones used instead.
Apt failed to update indexes!
pi@raspberrypi:~ $ ...............
pi@raspberrypi:~ $
pi@raspberrypi:~ $ curl -sSL
https://raw.githubusercontent.com/pimoroni/hyperpixel4/master/hyperpixel4-debug.sh
| bash

## Platform Information

Revision        : a02082
Description:    Raspbian GNU/Linux 8.0 (jessie)
4.1.18-v7+

## Touchscreen logs

Rectangular: Goodix
Square: ft5

## I2C Devices and Mappings

ls: cannot access /dev/i2c-*: No such file or directory

bash: line 24: i2cdetect: command not found

## Boot Config

# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# NOOBS Auto-generated Settings:
hdmi_force_hotplug=1
pi@raspberrypi:~ $

**PLEASE NOTE**

:warning: GitHub issues are for reporting problems with the software, tech support do not monitor these.
Our software team are smol and busy, and you will not receive a timely response.
If you're having a hardware issue with your Hyperpixel 4, you should contact support@pimoroni.com.

:warning: Hyperpixel 4 is only officially supported on Raspberry Pi OS. There are too many operating systems with too many quirks to begin to support them all. Issues relating to other operating systems will be closed.

**Describe the bug**

What's gone wrong?

**To Reproduce**

What install steps did you go through so far? Did you install from GitHub or use our one-line-installer?

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular?
2. Touch or non Touch?
3. Approximately when was it purchased
4. How is it connected to your Pi

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly
2. Which OS release are you using: `lsb_release --description` and `uname -r`
3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?

**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
* `dmesg | grep ft5` for HyperPixel 4.0" Square

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by helgibbons** [comment]
Closing as I think we sorted this one on the forums :)

The apt errors were fixed by upgrading to a new version of Raspberry Pi OS.
