### ISSUE TITLE
Hyperpixel and GPU Acceleration

### ISSUE THREAD

**Issue by baesek** [pimoroni/hyperpixel4#156]
Hi there,
I am using a Pi Zero 2W With raspbian-buster-lite 32bit running a chromium kiosk on a Hyperpixel 4.0 without Touch screen.
As I am running a animation on it, I am wondering if I can somehow make use of the GPU Acceleration to improve Performance.
When I go to the raspi-config and enable the fake KMS or full KMS driver the Hyperpixel stays black on next boot. 

Is there no way to use the fake KMS driver to also support OpenGL based Applications ?

Thank you for any info on that.

-baesek

**Comment by Gadgetoid** [comment]
This worked on Pi 4, meaning something has changed on the Pi Zero W2 to break it.

Full KMS support via Raspbian Bullseye is a work in progress and will be the *one true way* to do OpenGL over a DPI display on the Pi afaik. Unfortunately we have been at the whim of whatever contrived stop-gap solution the Pi has used for video prior to the full KMS support, so everything is a hot mess right now.

See: https://github.com/pimoroni/hyperpixel4/issues/155

Actually the full KMS very alpha solution mentioned in the issue above (https://github.com/pimoroni/hyperpixel4/issues/155#issuecomment-966455983) might work for Bullseye on the Zero 2W. I don't know! This stuff has blindsided me.

**Comment by baesek** [comment]
Thank you for your response!
So I will try out bullseye. But As it is in "alpha" state, I am afraid that there might be complicated problems popping up when i put this into my small unattended product. Do I understand this right, that with buster it is not possible to use any hardware acceleration at the moment? (Sorry I am having problems understanding technical descriptions in english sometimes, because it is not my native language)

**Comment by Gadgetoid** [comment]
I think to put it simply, the only thing I know is that: I don't know.

I'm still going through the process of trying to find answers to these problems.

**Comment by baesek** [comment]
Okay, I will post here, if It worked on zero 2
