### ISSUE TITLE
cURL one-line installer hangs

### ISSUE THREAD

**Issue by davidk** [pimoroni/hyperpixel4#16]
Hello!

I've encountered a small hang in HyperPixel4's one-line curl installer: `curl https://get.pimoroni.com/hyperpixel4 | bash`. (Unrelated to the `install.sh` utility in this repository).

I couldn't find the script in a Pimoroni repository to pull against, so hopefully this issue/repo is close enough.

During the cleanup routine, `rm -r /home/pi/Pimoroni/hyperpixel4` tries to remove the cloned
hyperpixel4 repository, but quietly waits on the following during cleanup:

`rm: remove write-protected regular file 'Pimoroni/hyperpixel4/.git/objects/ab/c93c7c0142a460fbe3452900af1eeb910a2bc8'?`

The culprit seems to be on line 1100: `cd $installdir && rm -r $installdir/$gitclonedir &> /dev/null`. The install finishes properly, but waits here forever, which might be the cause of confusion for some users.

**Comment by Gadgetoid** [comment]
Thanks for the thorough bug report- I've added an `f` flag to this step to avoid the silenced prompt.
