### ISSUE TITLE
Anyone have issues with Hyperpixel square non touch purchased a month ago with Raspberry Pi Zero 2?


### ISSUE THREAD

**Issue by raykanani** [pimoroni/hyperpixel4#166]
Currently shows boot up and then disappears. 

Video here https://twitter.com/raykanani/status/1492243290753798148?t=KXtkdjXh2O8E7ZdaNtPWrQ&s=19

Thanks for the help 🙂

**Comment by Gadgetoid** [comment]
Is this on Raspberry Pi OS Bullseye?

**Comment by raykanani** [comment]
Yes, it is the latest OS.

**Comment by raykanani** [comment]
Okay, I see now. I'll try with Buster OS

**Comment by Gadgetoid** [comment]
Sorry, Bullseye/64bit support is *coming* :grimacing:

**Comment by raykanani** [comment]
No worries. I appreciate the support 🙂
