### ISSUE TITLE
Hyperpixel 4.0 v1.3 Rock Pi Android support

### ISSUE THREAD

**Issue by Slarti01** [pimoroni/hyperpixel4#170]
Please excuse my ignorance here but is there a way I can get Android 10 rotted to support the Hyperpixel 4.0 on the Rock Pi 4B In portrait,  Any ideas assistance greatly apprecated

**Comment by ageeandakeyboard** [comment]
Hi,
I'm sorry to say that the Rock Pi 4B is not one of the platforms that we officially support. 
All of our code to initialize the is available if there is someone in the Rock Pi community that could adapt it but please be aware this would be purely experiment.

Regards
Gee
