### ISSUE TITLE
Touch doesn't work at the top

### ISSUE THREAD

**Issue by ACD-1** [pimoroni/hyperpixel4#19]
Hello,
my HyperPixel 4 display actually works quite well, except for the top about 7mm (with 180 ° screen rotation). At the top, the touch almost does not work. Is this a driver buy, do I have to calibrate the touch or a hardware defect?
If the Dektop menu is upper, then you can not really serve anything. Nothing happens with a display touch in the upper area.

Without the display rotation, the bottom does not work, ie the same place on the touch.

**Comment by Gadgetoid** [comment]
I've now merged the changes from https://github.com/pimoroni/hyperpixel4/pull/37/files into the Raspberry Pi 3B+ support branch of HyperPixel4. This switches to using a file in `/etc/udev/rules.d/` for touchscreen calibration, in lieu of dtoverlay parameters. It also includes a new `hyperpixel4-rotate` utility that sets both the touchscreen config and `display_rotate` together for 0, 90, 180 and 270 degree rotations.

If you're using a Pi 3B and still having trouble, it might be worth giving this a try. Instructions are here: https://github.com/pimoroni/hyperpixel4/tree/pi3
