### ISSUE TITLE
Hyperpixel4 does not work properly with pygame when screen is rotated into landscape mode

### ISSUE THREAD

**Issue by berarduc** [pimoroni/hyperpixel4#193]
I'm using hyperpixel 4 rectangular version. I've tried this with both buster (32-bit) and bullseye (both 32 and 64 bit versions).
latest versions of each - running sudo apt-get update if necessary to get the latest code.
In all cases the portrait (default) mode appears to work. also, in all cases, when I rotate the screen into landscape mode (using either hyperpixel4-rotate for the legacy version, or simply typing the proper lines into /boot/config.sys for bullseye), pygame will not open a FULLSCREEN, borderless, window properly. In all cases the window is offset down by 1/3 of the screen. 
Note the desktop appears FINE in all cases, yet pygame can't seem to understand the screen dimensions properly for fullscreen operation.

This problem can be reproduced easily by running the following simple python code (sorry proper indentation is not shown):

import pygame
from pygame import FULLSCREEN
import time 

def main():
    pygame.init()
    screen = pygame.display.set_mode([0,0],FULLSCREEN)
    screen.fill((0xff,0,0))
    pygame.display.flip()
    time.sleep(2)
main()

--> working properly, this program should open a fullscreen window, fill it with the color red, wait 2 secs, and then exit. This appears to work properly in portrait mode, but when rotated into landscape mode, the top 1/3 of the screen is black, indicating that pygame did not fill it and therefore did not recognize it as a proper portion of the display surface. 

Any help would be greatly appreciated.

Thanks.

Tom

**Comment by Gadgetoid** [comment]
I believe this is due to Pygame - or, perhaps, the underlying SDL - simply not supporting arbitrary screen resolutions.

Upgrading pygame and SDL might help. See: https://github.com/pimoroni/hyperpixel2r-python/issues/2
