### ISSUE TITLE
Odroid (C2, UX4) Tinker Board S, Rock Pi 4 Support 

### ISSUE THREAD

**Issue by cedrickzepp** [pimoroni/hyperpixel4#20]
I have several of the SBC mentioned above, I would like to know if there is the possibility of compatibility of your beautiful screen with the others.https://guides.github.com/features/mastering-markdown/
![c2_j2](https://user-images.githubusercontent.com/47735589/55302169-2be88200-53fd-11e9-892d-dce1e08c0275.png)
![xu4_con10](https://user-images.githubusercontent.com/47735589/55302222-75d16800-53fd-11e9-91e8-e56da9d43b12.png)
![asus-tinker-board-gpio-connector-01](https://user-images.githubusercontent.com/47735589/55302318-d2cd1e00-53fd-11e9-9e5e-469e81d51e19.jpg)
![Gpio_card](https://user-images.githubusercontent.com/47735589/55302357-0314bc80-53fe-11e9-8528-1c76048b383f.png)

**Comment by mikekscholz** [comment]
I can’t comment on the driver side of things but these boards would have to support the alternate dpi pinout configuration, it changes the default functions of the pins. https://pinout.xyz/pinout/dpi

**Comment by Gadgetoid** [comment]
I believe the chances of first-party support on anything but the Pi are basically zero. Ignoring the DPI outputs potentially being non-existent on other boards, as (currently) the sole wrangler of software I simply don't have the time to get up to speed enough with any other board to support it in any useful way.
