### ISSUE TITLE
Screen content rotated by 90 degrees and backwards

### ISSUE THREAD

**Issue by raju-bitter** [pimoroni/hyperpixel4#23]
I did a fresh install of Raspian with the Hyperpixel display. The script for installing the drivers went through without any problems, but once I booted, all the the screen content was rotated by 90 degrees, the height of the screen was incorrect (lower 40% showed pixel noise), and all the pixels were backward. See the screenshot.
![image](https://user-images.githubusercontent.com/296926/57441725-cf258600-724a-11e9-8952-1f411bff5208.png)
Before the upgrade the display was working fine with a version of the software I had installed in August 2018.
Hardware: Raspberry Pi 3 Model B
Raspbian version used: 2019-04-08-raspbian-stretch.zip

**Comment by mikekscholz** [comment]
That looks like the older hyperpixel to me, not the 4inch one. theres a different firmware on here just called hyperpixel not hyperpixel4, I dont believe theyre cross-compatible.

**Comment by Gadgetoid** [comment]
This is correct- you need the driver from here: https://github.com/pimoroni/hyperpixel
