### ISSUE TITLE
`hyperpixel4-rotate` should probably set DISPLAY=:0.0 for use over SSH

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/hyperpixel4#27]
I'm not entirely sure what the etiquette is in Linux for targeting a specific display when one is not set, but in the case of the Pi 4 I don't believe there's any harm in always assuming `DISPLAY=:0.0`, or setting this variable only when it's not otherwise set in th ecalling env. This would allow `hyperpixel4-rotate` to run over SSH without users having to worry about prepending a display variable.

**Comment by svanstrom** [comment]
As someone that just ran into this problem (and still feeling stupid about it), I'd suggest that instead of silently fixing this the user is instead hit with an appropriate, educational, error message.

**Comment by locki-cz** [comment]
problem solved: https://youtu.be/OJ59hXSyBoI?t=674
