### ISSUE TITLE
Screen not reacting on after going to sleep

### ISSUE THREAD

**Issue by R0B3RDV** [pimoroni/hyperpixel4#43]
I'm having issues (and this is the 3rd clean installation - buster full) when the screen goes to power saving or standby, it will not get back on again (maybe has something to do with the heat issue - no touch reaction).

**Comment by Gadgetoid** [comment]
This must be related to your wider problems with touch, since I've always been able to wake from standby with a touch. If you ssh in while it's in this state and run `dmesg` do you see any communication errors with the touchscreen?

**Comment by Gadgetoid** [comment]
Any luck with your screen waking from sleep?
