### ISSUE TITLE
Hyperpixel Square CM3+ Support 

### ISSUE THREAD

**Issue by neomi19** [pimoroni/hyperpixel4#56]
Hello, 

I designed a board with the CM3+ to fit the Hyperpixel 4.0 Square. 
Will your Hyperpixel drivers work or do i need to write a new driver for the CM3+. 
If so, which driver should I download for the CM3+?

KR
Neomi

**Comment by Gadgetoid** [comment]
We don't officially support the HyperPixel on CM3+ since there are too many unknowns involved in the design of carrier board. I believe, however, you've reached out to our engineering department, so I'll close this for now.
