### ISSUE TITLE
Please build the latest overlays?

### ISSUE THREAD

**Issue by drewcovi** [pimoroni/hyperpixel4#7]
I'm unfortunately stuck in a situation where I don't have immediate access to a Raspbian instance (using Resin.io). 

I assume the only reason we're required to build to get rotation support is just a lack of time-on-hand... has anyone out there built it yet, so we can get a pull request and the latest overlay in the dist directory?

Thanks!

**Comment by Gadgetoid** [comment]
I found out from the change I reverted that prebuilt overlays are prone to failure on anything but the distribution they were built on.

I will have to modify the installer to compile the overlay from source for the target distribution, otherwise some percentage of users will run into problems.

**Comment by drewcovi** [comment]
Thanks!
