### ISSUE TITLE
Impossible to rotate display

### ISSUE THREAD

**Issue by Jiheffe** [pimoroni/hyperpixel4#80]
**Describe the bug**

hyperpixel4-rotate does not work on a PI4 wirth Octopi. Thne touch interface seems to rotate but not the screen itself. When you touch the screen, it positions the cursor at the right place, should the screen have rotated correctly.

**To Reproduce**

Fresh install (Etcher) of Octopi.
Installed desktop (not installed by defazult with Octopi)
Upgraded all packages
Unstalled Hyperpixel

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Rectangular
2. Touch
3. Purchased last week
4. Connected to PI4 with provided connector

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly
pi@octopi:~ $ cat /proc/cpuinfo | grep Revision
Revision	: c03112
pi@octopi:~ $ 
2. Which OS release are you using: `lsb_release --description` and `uname -r`
pi@octopi:~ $ lsb_release --description
Description:	Raspbian GNU/Linux 10 (buster)
pi@octopi:~ $ uname -r
4.19.118-v7l+
3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
Fresh
**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
* `dmesg | grep ft5` for HyperPixel 4.0" Square

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by Gadgetoid** [comment]
What's the default `/boot/config.txt` for Octopi? Does it have the new V3D driver for Pi 4?

Persisting Display rotation is handled by hooking the Raspberry Pi display configuration utility, which is suboptimal but does the trick. Under the hood, though, I recall this is just a GUI for `xrandr`.

Do you have `xrandr` installed, and does running `xrandr --output DSI-1 --rotate <left/right/normal/inverted>` have any effect?
