### ISSUE TITLE
Weird banding using Hyperpixel Rectangular with RPi4

### ISSUE THREAD

**Issue by docbobo** [pimoroni/hyperpixel4#82]
**Describe the bug**

From the moment the RPi4 enables video output, there is weird band of colors on the screen, which fades out after a while. However, it seems to reappear whenever significant changes are made to the screen output.

![IMG_0651](https://user-images.githubusercontent.com/1257060/86791304-b2145f00-c069-11ea-8db4-2da690cd6e74.jpeg)

**To Reproduce**

Always happens for me.

**Your HyperPixel 4**

Hyperpixel 4 Rectangular on a RPi  4. Bought December 2019, never used until now.

**Your Raspberry Pi**

RPi4, 4GB. Running latest version of OctoPi.

**Comment by Gadgetoid** [comment]
Whoa- I can't say I've seen this before.

It could- potentially- be related to something else running on the Pi, but I don't quite see how.

I'll ask our engineers/testers to see if anything like this has cropped up.

**Comment by docbobo** [comment]
It does happen immediately when the system starts up, right when the raspberries appear at the top. So I suspect it’s not related to anything running in the Pi. 

The RPi4 is one of the very first, btw.

**Comment by Gadgetoid** [comment]
I think it's probably a hardware issue with the screen. You should drop an email to support@pimoroni.com to proceed.
