### ISSUE TITLE
Flickering HyperPixel 4.0 Square

### ISSUE THREAD

**Issue by jzting** [pimoroni/hyperpixel4#91]
**Describe the bug**

The screen has a noticeable flickering. This issue started happening just recently.

See attached videos (recorded at 60fps and 240fps): [hyperpixel-flickering.zip](https://github.com/pimoroni/hyperpixel4/files/5001957/hyperpixel-flickering.zip)

Also note the ghosted scanlines when the display first turns on:
[hyperpixel-ghosting.zip](https://github.com/pimoroni/hyperpixel4/files/5001985/hyperpixel-ghosting.zip)

**To Reproduce**

Installed from one-line-installer. This happens all the time now, e.g. when playing images or video using Openframe or fbi.

**Your HyperPixel 4**

1. Square
2. Touch
3. May 15, 2020
4. RPI Zero W

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. 9000c1
2. Raspbian GNU/Linux 10 (buster) 4.19.66+
3. From an Openframe image (https://gist.github.com/jvolker/96a52b05459316643f8e110ff46b8e32)

**Comment by Gadgetoid** [comment]
I'll ping the folks in our engineering/testing department to see if they've seen anything like this.

It might be worth contacting support@pimoroni.com - since I don't think this is a software issue, and they'll be better equipped to replace your unit if required.

**Comment by Sawtaytoes** [comment]
I'm in the same boat.

Mine was working perfectly fine with a Raspberry Pi Zero 2 W. When I took it out and put in a 4 model B, I'm experiencing the same issues.

Could it be a software issue or did I break something when swapping to the larger Pi?
